package one.empty3.apps.mylittlesynth;

import javax.swing.*;

public class MainApp {
    private JPanel panel1;
    private JButton a1Button;
    private JButton a1Button1;
    private JButton a2Button;
    private JButton a3Button1;
    private JButton a4Button1;
    private JButton a5Button;
    private JButton a6Button1;
    private JButton a7Button1;
    private JButton a8Button1;
    private JButton a1Button2;
    private JButton a2Button1;
    private JButton a3Button;
    private JButton a4Button;
    private JButton a5Button1;
    private JButton a6Button;
    private JButton a7Button;
    private JButton a8Button;
    private JSpinner octave;
    private JTable table1;
    private JScrollBar scrollBar2;
    private JButton a9Button;
    private JButton a9Button1;
    private JButton a10Button2;
    private JButton a10Button;
    private JButton a11Button1;
    private JButton STARTButton;
    private JButton a11Button;
    private JButton STOPButton;
    private JButton a9Button2;
    private JButton a10Button1;
    private JButton a11Button2;
    private JButton a12Button2;
    private JButton a12Button1;
    private JButton a12Button;
    private JList list1;
    private JButton bButton;
    private JButton gButton;
    private JButton aButton;
    private JButton fButton;
    private JButton dButton;
    private JButton cButton;
    private JButton eButton;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;
    private JButton button8;
    private JButton button9;
    private JButton button10;
    private JButton button11;
}
